---
- import_playbook: "set_atscale_variables.yml"

- name: Apply the krb5-client role and atscale role to the atscale-server group
  hosts: atscale-server
  any_errors_fatal: true
  become: yes
  roles:
    - role: atscale
