---
- name: Create the required Ansible groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add nodes to the hadoop-cluster group and groups representing the host_groups
      include_tasks: "clouds/add_nodes_{{ cloud_name }}.yml"
      with_items: "{{ nodes|default(omit) }}"

    - name: Initialize the ambari_groups and atscale_groups lists
      set_fact:
        atscale_groups: []

    - block:
        - name: Populate the atscale_groups list (dynamic blueprint)
          set_fact:
            atscale_groups: "{{ atscale_groups }} + [ '{{ item.host_group }}' ]"
          when: groups[item.host_group] is defined and groups[item.host_group]|length > 0 and 'ATSCALE' in item.services
          with_items: "{{ blueprint_dynamic }}"
          no_log: False

    - name: Fail if the atscale_groups list is empty
      fail:
        msg: "The atscale_groups list is empty. This usually means there is no 'ATSCALE' component defined in the blueprint or there is no Ansible inventory group corresponding with the name of the blueprint's host_group."
      when: atscale_groups|length == 0

    - name: Fail if there is no Ansible inventory group matching the blueprint's host_groups
      fail:
        msg: "The {{ item }} host_group is defined in the blueprint but there is no matching Ansible inventory group called {{ item }} or there are no hosts in this group."
      when: groups[item] is not defined or groups[item]|length == 0
      with_items: "{{ atscale_groups }}"


    - name: Add nodes to the atscale-server group
      add_host:
        name: "{{ groups[atscale_groups|first]|first }}"
        groups: "atscale-server"